{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d9f0fc23",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Load your dataset from the specified path\n",
    "df = pd.read_csv(r'C:\\Users\\admin\\Desktop\\DSBDA\\Dataset.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "cc1bc178",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "       id               brand  \\\n",
      "0    1048           colourpop   \n",
      "1    1047           colourpop   \n",
      "2    1046           colourpop   \n",
      "3    1045           colourpop   \n",
      "4    1044               boosh   \n",
      "..    ...                 ...   \n",
      "926     5            pacifica   \n",
      "927     4  physicians formula   \n",
      "928     3  physicians formula   \n",
      "929     2                 NaN   \n",
      "930     1          pure anada   \n",
      "\n",
      "                                                  name  price price_sign  \\\n",
      "0                                        Lippie Pencil   5.00          $   \n",
      "1                                          Blotted Lip   5.50          $   \n",
      "2                                          Lippie Stix   5.50          $   \n",
      "3                                 No Filter Foundation  12.00          $   \n",
      "4                                             Lipstick  26.00          $   \n",
      "..                                                 ...    ...        ...   \n",
      "926  Pacifica Stellar Gaze Length & Strength Minera...  28.00        NaN   \n",
      "927    Physicians Formula Organic Wear FakeOut Mascara  15.79        NaN   \n",
      "928  Physicians Formula Organic Wear Lash Boosting ...  15.79        NaN   \n",
      "929                  L' Oreal Paris Voluminous Mascara   9.99        NaN   \n",
      "930                         Pure Anada Natural Mascara  14.00        NaN   \n",
      "\n",
      "    currency                                         image_link  \\\n",
      "0        CAD  https://cdn.shopify.com/s/files/1/1338/0845/co...   \n",
      "1        CAD  https://cdn.shopify.com/s/files/1/1338/0845/pr...   \n",
      "2        CAD  https://cdn.shopify.com/s/files/1/1338/0845/co...   \n",
      "3        CAD  https://cdn.shopify.com/s/files/1/1338/0845/pr...   \n",
      "4        CAD  https://cdn.shopify.com/s/files/1/1016/3243/pr...   \n",
      "..       ...                                                ...   \n",
      "926      NaN  https://d3t32hsnjxo7q6.cloudfront.net/i/b4a5f3...   \n",
      "927      NaN  https://d3t32hsnjxo7q6.cloudfront.net/i/2b3d55...   \n",
      "928      NaN  https://d3t32hsnjxo7q6.cloudfront.net/i/ca3136...   \n",
      "929      NaN  https://d3t32hsnjxo7q6.cloudfront.net/i/4d671a...   \n",
      "930      NaN  https://d3t32hsnjxo7q6.cloudfront.net/i/afefed...   \n",
      "\n",
      "                                          product_link  \\\n",
      "0      https://colourpop.com/collections/lippie-pencil   \n",
      "1    https://colourpop.com/collections/lippie-stix?...   \n",
      "2        https://colourpop.com/collections/lippie-stix   \n",
      "3    https://colourpop.com/products/no-filter-matte...   \n",
      "4                 https://www.boosh.ca/collections/all   \n",
      "..                                                 ...   \n",
      "926  https://well.ca/products/pacifica-stellar-gaze...   \n",
      "927  https://well.ca/products/physicians-formula-or...   \n",
      "928  https://well.ca/products/physicians-formula-or...   \n",
      "929  https://well.ca/products/l-oreal-paris-volumin...   \n",
      "930  https://well.ca/products/pure-anada-natural-ma...   \n",
      "\n",
      "                                          website_link  \\\n",
      "0                                https://colourpop.com   \n",
      "1                                https://colourpop.com   \n",
      "2                                https://colourpop.com   \n",
      "3    https://colourpop.com/products/no-filter-matte...   \n",
      "4                                https://www.boosh.ca/   \n",
      "..                                                 ...   \n",
      "926                                    https://well.ca   \n",
      "927                                    https://well.ca   \n",
      "928                                    https://well.ca   \n",
      "929                                    https://well.ca   \n",
      "930                                    https://well.ca   \n",
      "\n",
      "                                           description    rating  category  \\\n",
      "0    Lippie Pencil A long-wearing and high-intensit...  4.319118    pencil   \n",
      "1    Blotted Lip Sheer matte lipstick that creates ...  4.319118  lipstick   \n",
      "2    Lippie Stix Formula contains Vitamin E, Mango,...  4.319118  lipstick   \n",
      "3    Developed for the Selfie Age, our buildable fu...  4.319118    liquid   \n",
      "4    All of our products are free from lead and hea...  4.319118  lipstick   \n",
      "..                                                 ...       ...       ...   \n",
      "926  You will fall in love with Pacifica's long las...  4.200000       NaN   \n",
      "927  Physicians Formula Organic Wear FakeOut Mascar...  3.900000       NaN   \n",
      "928  Physicians Formula Organic Wear Lash Boosting ...  3.700000       NaN   \n",
      "929  Voluminous - Volume Building Waterproof Mascar...  4.500000       NaN   \n",
      "930  Finally, a natural mascara you can feel good a...  4.600000       NaN   \n",
      "\n",
      "    product_type                                tag_list  \\\n",
      "0      lip_liner               ['cruelty free', 'Vegan']   \n",
      "1       lipstick               ['cruelty free', 'Vegan']   \n",
      "2       lipstick               ['cruelty free', 'Vegan']   \n",
      "3     foundation               ['cruelty free', 'Vegan']   \n",
      "4       lipstick            ['Chemical Free', 'Organic']   \n",
      "..           ...                                     ...   \n",
      "926      mascara                    ['Natural', 'Vegan']   \n",
      "927      mascara              ['Natural', 'Gluten Free']   \n",
      "928      mascara              ['Natural', 'Gluten Free']   \n",
      "929      mascara                                      []   \n",
      "930      mascara  ['Natural', 'Gluten Free', 'Canadian']   \n",
      "\n",
      "                   created_at                updated_at  \\\n",
      "0    2018-07-08T23:45:08.056Z  2018-07-09T00:53:23.301Z   \n",
      "1    2018-07-08T22:01:20.178Z  2018-07-09T00:53:23.287Z   \n",
      "2    2018-07-08T21:47:49.858Z  2018-07-09T00:53:23.274Z   \n",
      "3    2018-07-08T18:22:25.273Z  2018-07-09T00:53:23.313Z   \n",
      "4    2018-07-08T17:32:28.088Z  2018-09-02T22:52:06.669Z   \n",
      "..                        ...                       ...   \n",
      "926  2016-10-01T18:10:52.756Z  2017-12-23T20:31:47.230Z   \n",
      "927  2016-10-01T18:10:51.387Z  2017-12-23T20:31:47.075Z   \n",
      "928  2016-10-01T18:10:50.417Z  2017-12-23T20:31:46.951Z   \n",
      "929  2016-10-01T18:10:49.185Z  2017-12-23T20:31:46.436Z   \n",
      "930  2016-10-01T18:10:46.893Z  2017-12-23T20:31:46.013Z   \n",
      "\n",
      "                                       product_api_url  \\\n",
      "0    http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "1    http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "2    http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "3    http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "4    http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "..                                                 ...   \n",
      "926  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "927  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "928  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "929  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "930  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "\n",
      "                                    api_featured_image  \\\n",
      "0    //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "1    //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "2    //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "3    //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "4    //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "..                                                 ...   \n",
      "926  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "927  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "928  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "929  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "930  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "\n",
      "                                        product_colors  \n",
      "0    [{'hex_value': '#B28378', 'colour_name': 'BFF ...  \n",
      "1    [{'hex_value': '#b72227', 'colour_name': \"Bee'...  \n",
      "2    [{'hex_value': '#F2DEC3', 'colour_name': 'Fair...  \n",
      "3    [{'hex_value': '#F2DEC3', 'colour_name': 'Fair...  \n",
      "4    [{'hex_value': '#CB4975', 'colour_name': 'Babs...  \n",
      "..                                                 ...  \n",
      "926                                                 []  \n",
      "927  [{'hex_value': '#000000', 'colour_name': 'Ultr...  \n",
      "928  [{'hex_value': '#000000', 'colour_name': 'Ultr...  \n",
      "929  [{'hex_value': '#231F20', 'colour_name': 'Blac...  \n",
      "930  [{'hex_value': '#000000', 'colour_name': 'Blac...  \n",
      "\n",
      "[931 rows x 19 columns]\n"
     ]
    }
   ],
   "source": [
    "df = df.drop_duplicates()\n",
    "\n",
    "\n",
    "print(df)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "06ad6cb1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "     id      brand           name  price price_sign currency  \\\n",
      "0  1048  colourpop  Lippie Pencil    5.0          $      CAD   \n",
      "1  1047  colourpop    Blotted Lip    5.5          $      CAD   \n",
      "\n",
      "                                          image_link  \\\n",
      "0  https://cdn.shopify.com/s/files/1/1338/0845/co...   \n",
      "1  https://cdn.shopify.com/s/files/1/1338/0845/pr...   \n",
      "\n",
      "                                        product_link           website_link  \\\n",
      "0    https://colourpop.com/collections/lippie-pencil  https://colourpop.com   \n",
      "1  https://colourpop.com/collections/lippie-stix?...  https://colourpop.com   \n",
      "\n",
      "                                         description    rating  category  \\\n",
      "0  Lippie Pencil A long-wearing and high-intensit...  4.319118    pencil   \n",
      "1  Blotted Lip Sheer matte lipstick that creates ...  4.319118  lipstick   \n",
      "\n",
      "  product_type                   tag_list                created_at  \\\n",
      "0    lip_liner  ['cruelty free', 'Vegan']  2018-07-08T23:45:08.056Z   \n",
      "1     lipstick  ['cruelty free', 'Vegan']  2018-07-08T22:01:20.178Z   \n",
      "\n",
      "                 updated_at  \\\n",
      "0  2018-07-09T00:53:23.301Z   \n",
      "1  2018-07-09T00:53:23.287Z   \n",
      "\n",
      "                                     product_api_url  \\\n",
      "0  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "1  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "\n",
      "                                  api_featured_image  \\\n",
      "0  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "1  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "\n",
      "                                      product_colors  \n",
      "0  [{'hex_value': '#B28378', 'colour_name': 'BFF ...  \n",
      "1  [{'hex_value': '#b72227', 'colour_name': \"Bee'...  \n"
     ]
    }
   ],
   "source": [
    "#data integration\n",
    "df1=df.head(2)\n",
    "print(df1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "fe232945",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "     id       brand                               name  price price_sign  \\\n",
      "929   2         NaN  L' Oreal Paris Voluminous Mascara   9.99        NaN   \n",
      "930   1  pure anada         Pure Anada Natural Mascara  14.00        NaN   \n",
      "\n",
      "    currency                                         image_link  \\\n",
      "929      NaN  https://d3t32hsnjxo7q6.cloudfront.net/i/4d671a...   \n",
      "930      NaN  https://d3t32hsnjxo7q6.cloudfront.net/i/afefed...   \n",
      "\n",
      "                                          product_link     website_link  \\\n",
      "929  https://well.ca/products/l-oreal-paris-volumin...  https://well.ca   \n",
      "930  https://well.ca/products/pure-anada-natural-ma...  https://well.ca   \n",
      "\n",
      "                                           description  rating category  \\\n",
      "929  Voluminous - Volume Building Waterproof Mascar...     4.5      NaN   \n",
      "930  Finally, a natural mascara you can feel good a...     4.6      NaN   \n",
      "\n",
      "    product_type                                tag_list  \\\n",
      "929      mascara                                      []   \n",
      "930      mascara  ['Natural', 'Gluten Free', 'Canadian']   \n",
      "\n",
      "                   created_at                updated_at  \\\n",
      "929  2016-10-01T18:10:49.185Z  2017-12-23T20:31:46.436Z   \n",
      "930  2016-10-01T18:10:46.893Z  2017-12-23T20:31:46.013Z   \n",
      "\n",
      "                                       product_api_url  \\\n",
      "929  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "930  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "\n",
      "                                    api_featured_image  \\\n",
      "929  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "930  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "\n",
      "                                        product_colors  \n",
      "929  [{'hex_value': '#231F20', 'colour_name': 'Blac...  \n",
      "930  [{'hex_value': '#000000', 'colour_name': 'Blac...  \n"
     ]
    }
   ],
   "source": [
    "df2=df.tail(2)\n",
    "print(df2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "18be2889",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>brand</th>\n",
       "      <th>name</th>\n",
       "      <th>price</th>\n",
       "      <th>price_sign</th>\n",
       "      <th>currency</th>\n",
       "      <th>image_link</th>\n",
       "      <th>product_link</th>\n",
       "      <th>website_link</th>\n",
       "      <th>description</th>\n",
       "      <th>rating</th>\n",
       "      <th>category</th>\n",
       "      <th>product_type</th>\n",
       "      <th>tag_list</th>\n",
       "      <th>created_at</th>\n",
       "      <th>updated_at</th>\n",
       "      <th>product_api_url</th>\n",
       "      <th>api_featured_image</th>\n",
       "      <th>product_colors</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>926</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>927</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>928</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>929</th>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>930</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>931 rows × 19 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        id  brand   name  price  price_sign  currency  image_link  \\\n",
       "0    False  False  False  False       False     False       False   \n",
       "1    False  False  False  False       False     False       False   \n",
       "2    False  False  False  False       False     False       False   \n",
       "3    False  False  False  False       False     False       False   \n",
       "4    False  False  False  False       False     False       False   \n",
       "..     ...    ...    ...    ...         ...       ...         ...   \n",
       "926  False  False  False  False        True      True       False   \n",
       "927  False  False  False  False        True      True       False   \n",
       "928  False  False  False  False        True      True       False   \n",
       "929  False   True  False  False        True      True       False   \n",
       "930  False  False  False  False        True      True       False   \n",
       "\n",
       "     product_link  website_link  description  rating  category  product_type  \\\n",
       "0           False         False        False   False     False         False   \n",
       "1           False         False        False   False     False         False   \n",
       "2           False         False        False   False     False         False   \n",
       "3           False         False        False   False     False         False   \n",
       "4           False         False        False   False     False         False   \n",
       "..            ...           ...          ...     ...       ...           ...   \n",
       "926         False         False        False   False      True         False   \n",
       "927         False         False        False   False      True         False   \n",
       "928         False         False        False   False      True         False   \n",
       "929         False         False        False   False      True         False   \n",
       "930         False         False        False   False      True         False   \n",
       "\n",
       "     tag_list  created_at  updated_at  product_api_url  api_featured_image  \\\n",
       "0       False       False       False            False               False   \n",
       "1       False       False       False            False               False   \n",
       "2       False       False       False            False               False   \n",
       "3       False       False       False            False               False   \n",
       "4       False       False       False            False               False   \n",
       "..        ...         ...         ...              ...                 ...   \n",
       "926     False       False       False            False               False   \n",
       "927     False       False       False            False               False   \n",
       "928     False       False       False            False               False   \n",
       "929     False       False       False            False               False   \n",
       "930     False       False       False            False               False   \n",
       "\n",
       "     product_colors  \n",
       "0             False  \n",
       "1             False  \n",
       "2             False  \n",
       "3             False  \n",
       "4             False  \n",
       "..              ...  \n",
       "926           False  \n",
       "927           False  \n",
       "928           False  \n",
       "929           False  \n",
       "930           False  \n",
       "\n",
       "[931 rows x 19 columns]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.isnull()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "86b9b7d6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "id                    False\n",
       "brand                  True\n",
       "name                  False\n",
       "price                 False\n",
       "price_sign             True\n",
       "currency               True\n",
       "image_link            False\n",
       "product_link          False\n",
       "website_link          False\n",
       "description            True\n",
       "rating                False\n",
       "category               True\n",
       "product_type          False\n",
       "tag_list              False\n",
       "created_at            False\n",
       "updated_at            False\n",
       "product_api_url       False\n",
       "api_featured_image    False\n",
       "product_colors        False\n",
       "dtype: bool"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.isna().any()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "4aed1907",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "id                      0\n",
       "brand                  12\n",
       "name                    0\n",
       "price                   0\n",
       "price_sign            563\n",
       "currency              563\n",
       "image_link              0\n",
       "product_link            0\n",
       "website_link            0\n",
       "description            25\n",
       "rating                  0\n",
       "category              424\n",
       "product_type            0\n",
       "tag_list                0\n",
       "created_at              0\n",
       "updated_at              0\n",
       "product_api_url         0\n",
       "api_featured_image      0\n",
       "product_colors          0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.isna().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "6caf50e6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Union:\n",
      "     id       brand                               name  price price_sign  \\\n",
      "0  1048   colourpop                      Lippie Pencil   5.00          $   \n",
      "1  1047   colourpop                        Blotted Lip   5.50          $   \n",
      "2     2         NaN  L' Oreal Paris Voluminous Mascara   9.99        NaN   \n",
      "3     1  pure anada         Pure Anada Natural Mascara  14.00        NaN   \n",
      "\n",
      "  currency                                         image_link  \\\n",
      "0      CAD  https://cdn.shopify.com/s/files/1/1338/0845/co...   \n",
      "1      CAD  https://cdn.shopify.com/s/files/1/1338/0845/pr...   \n",
      "2      NaN  https://d3t32hsnjxo7q6.cloudfront.net/i/4d671a...   \n",
      "3      NaN  https://d3t32hsnjxo7q6.cloudfront.net/i/afefed...   \n",
      "\n",
      "                                        product_link           website_link  \\\n",
      "0    https://colourpop.com/collections/lippie-pencil  https://colourpop.com   \n",
      "1  https://colourpop.com/collections/lippie-stix?...  https://colourpop.com   \n",
      "2  https://well.ca/products/l-oreal-paris-volumin...        https://well.ca   \n",
      "3  https://well.ca/products/pure-anada-natural-ma...        https://well.ca   \n",
      "\n",
      "                                         description    rating  category  \\\n",
      "0  Lippie Pencil A long-wearing and high-intensit...  4.319118    pencil   \n",
      "1  Blotted Lip Sheer matte lipstick that creates ...  4.319118  lipstick   \n",
      "2  Voluminous - Volume Building Waterproof Mascar...  4.500000       NaN   \n",
      "3  Finally, a natural mascara you can feel good a...  4.600000       NaN   \n",
      "\n",
      "  product_type                                tag_list  \\\n",
      "0    lip_liner               ['cruelty free', 'Vegan']   \n",
      "1     lipstick               ['cruelty free', 'Vegan']   \n",
      "2      mascara                                      []   \n",
      "3      mascara  ['Natural', 'Gluten Free', 'Canadian']   \n",
      "\n",
      "                 created_at                updated_at  \\\n",
      "0  2018-07-08T23:45:08.056Z  2018-07-09T00:53:23.301Z   \n",
      "1  2018-07-08T22:01:20.178Z  2018-07-09T00:53:23.287Z   \n",
      "2  2016-10-01T18:10:49.185Z  2017-12-23T20:31:46.436Z   \n",
      "3  2016-10-01T18:10:46.893Z  2017-12-23T20:31:46.013Z   \n",
      "\n",
      "                                     product_api_url  \\\n",
      "0  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "1  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "2  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "3  http://makeup-api.herokuapp.com/api/v1/product...   \n",
      "\n",
      "                                  api_featured_image  \\\n",
      "0  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "1  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "2  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "3  //s3.amazonaws.com/donovanbailey/products/api_...   \n",
      "\n",
      "                                      product_colors  \n",
      "0  [{'hex_value': '#B28378', 'colour_name': 'BFF ...  \n",
      "1  [{'hex_value': '#b72227', 'colour_name': \"Bee'...  \n",
      "2  [{'hex_value': '#231F20', 'colour_name': 'Blac...  \n",
      "3  [{'hex_value': '#000000', 'colour_name': 'Blac...  \n",
      "Intersection:\n",
      "Empty DataFrame\n",
      "Columns: [id, brand, name, price, price_sign, currency, image_link, product_link, website_link, description, rating, category, product_type, tag_list, created_at, updated_at, product_api_url, api_featured_image, product_colors]\n",
      "Index: []\n"
     ]
    }
   ],
   "source": [
    "#integrating data by applying union and intersection\n",
    "union_df = pd.concat([df1, df2], ignore_index=True)\n",
    "intersection_df = pd.merge(df1, df2, how='inner')\n",
    "print(\"Union:\")\n",
    "print(union_df)\n",
    "\n",
    "print(\"Intersection:\")\n",
    "print(intersection_df)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d2e8cc17",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
